version: '3.8'

services:
  mongo:
    image: mongo:6.0.8-jammy
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=core
      - MONGO_INITDB_ROOT_USERNAME=adminuser
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - C:/Users/Nimit Bihari/OneDrive/Desktop/dump/08122023/mnt/data/mongodb:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
